//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTimeSlotTable
    {
        public int LabTimeSlotID { get; set; }
        public int LabID { get; set; }
        public string Name { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual LabTable LabTable { get; set; }
    }
}
