//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.DoctorTables = new HashSet<DoctorTable>();
            this.LabTables = new HashSet<LabTable>();
        }
    
        public int UserID { get; set; }
        public int UserTypeID { get; set; }
        [Required(ErrorMessage = "*Required")]

        public string UserName { get; set; }
        [Required(ErrorMessage = "*Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Email { get; set; }//TCKN
        [Required(ErrorMessage = "*Required")]
        [DataType(DataType.PhoneNumber)]
        public string ContactNo { get; set; }
        public string Description { get; set; }
        public bool IsVerifed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorTable> DoctorTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTable> LabTables { get; set; }
        public virtual UserTypeTable UserTypeTable { get; set; }
    }
}
